Protocol type version fix
SkylineCommunications/Skyline-DataMiner-Deploy-Action pull request #36
Opened 2023-05-31 15:04 UTC by janstaelensskyline

* Allows tagging with pre-release versions. (Note, will still fail until further fixes in upload API)
* Improves logging and exception logging for deployments and uploads
*

Note: Before release, first release Reusable Modules and adjust the NuGet Package for dmapp creation in the deploy action.

2023-06-05 09:59 UTC, MichielOda requested changes

2023-06-05 09:59 UTC, MichielOda commented on GitHubAction/UploadArtifactApi/HttpArtifactUploadApi.cs
> +        StringBuilder sb = new StringBuilder();
```suggestion
```

2023-06-05 09:59 UTC, MichielOda commented on GitHubAction/UploadArtifactApi/HttpArtifactUploadApi.cs
> +        StringBuilder sb = new StringBuilder();
Unused variable

2023-06-05 09:59 UTC, MichielOda commented on GitHubAction/UploadArtifactApi/HttpArtifactUploadApi.cs
> +            throw new KeyException($"The upload api returned a {response.StatusCode} response. Body:" + response?.Content?.ToString() ?? "null");
```suggestion
            throw new KeyException($"The upload api returned a {response.StatusCode} response. Body: {response.Content}");
```

2023-06-05 09:59 UTC, MichielOda commented on GitHubAction/UploadArtifactApi/HttpArtifactUploadApi.cs
> +        throw new UploadPackageException($"The upload api returned a {response.StatusCode} response. Body:" + response?.Content?.ToString() ?? "null");
```suggestion
        throw new UploadPackageException($"The upload api returned a {response.StatusCode} response. Body: {response.Content}");
```

2023-06-05 09:59 UTC, MichielOda commented on GitHubAction/UploadArtifactApi/HttpArtifactUploadApi.cs
> +            throw new KeyException($"The upload api returned a {response.StatusCode} response. Body:" + response?.Content?.ToString() ?? "null");
Content will never be null
![image](https://github.com/SkylineCommunications/Skyline-DataMiner-Deploy-Action/assets/97458010/88699f9b-1c5d-463e-95fa-41ca1d8ac7ce)

2023-06-05 09:59 UTC, MichielOda commented on GitHubAction/Package.Application/PackageService.cs
> +    public async Task<UploadedPackage> UploadPackageAsync(CreatedPackage createdPackage,string catalogVersion, string key)
```suggestion
    public async Task<UploadedPackage> UploadPackageAsync(CreatedPackage createdPackage, string catalogVersion, string key)
```

2023-06-06 09:57 UTC, janstaelensskyline commented on GitHubAction/GitHubAction.Console/Extensions/ApiExtensions.cs
> +            var presenter = s.GetService<ConsolePackagePresenter>();
removed.

2023-06-06 10:09 UTC, MichielOda submitted a review, later dismissed

2023-06-07 13:56 UTC, merged